export default {
  appTitle: 'Business Central Setup',
  splashWelcome: 'Welcome! This wizard will help you configure Dynamics 365 Business Central.',
  getStarted: 'Get Started',
  basicInfoTitle: 'Basic Information',
  companyNameLabel: 'Company Name',
  industryLabel: 'Industry',
  websiteLabel: 'Website URL',
  descriptionLabel: 'Description',
  descriptionHint: 'Please tell us information about your company. It should be tall enough for 8 lines of text. This will help in providing the best possible configuration.',
  next: 'Next',
  back: 'Back',
  selectConfigArea: 'Select a configuration area',
  companyInfo: 'Company Information',
  postingGroups: 'Posting Groups',
  paymentTerms: 'Payment Terms',
  generalPostingGroupLabel: 'General Posting Group',
  paymentTermsLabel: 'Terms',
  common: 'Common',
  additional: 'Additional',
  finishTitle: 'Finish',
  finishGeneratePrompt: 'Click below to generate your RapidStart file.',
  generate: 'Generate',
  fileCreated: 'File created:',
  debugLog: 'Debug Log',
  home: 'Home',
};
