export default {
  appTitle: 'Business Central Setup',
  splashWelcome: 'Welcome! This wizard will help you configure Dynamics 365 Business Central.',
  getStarted: 'Get Started',
  basicInfoTitle: 'Basic Information',
  basicInfo: 'Basics',
  companyNameLabel: 'Company Name',
  industryLabel: 'Industry',
  websiteLabel: 'Website URL',
  descriptionLabel: 'Description',
  descriptionHint: 'Please tell us information about your company. It should be tall enough for 8 lines of text. This will help in providing the best possible configuration.',
  next: 'Next',
  back: 'Back',
  selectConfigArea: 'Select a configuration area',
  companyInfo: 'Company Information',
  postingGroups: 'Posting Groups',
  paymentTerms: 'Payment Terms',
  generalLedgerSetup: 'General Ledger Setup',
  salesReceivablesSetup: 'Sales & Receivables Setup',
  generalPostingGroupLabel: 'General Posting Group',
  paymentTermsLabel: 'Terms',
  common: 'Common',
  sometimes: 'Sometimes',
  additional: 'Additional',
  customers: 'Customers',
  vendors: 'Vendors',
  items: 'Items',
  search: 'Search',
  help: 'Get Help from your Partner',
  review: 'Review',
  reviewAndFinish: 'Review and Finish',
  configurationData: 'Configuration Data',
  masterData: 'Master Data',
  finishTitle: 'Finish',
  finishGeneratePrompt: 'Click below to generate your RapidStart file.',
  generate: 'Generate',
  fileCreated: 'File created:',
  debugLog: 'Debug Log',
  home: 'Home',
  skip: 'Skip',
  allCommonComplete: 'All common fields completed',
  finishButton: 'Finish',
  bcFieldNameLabel: 'Business Central Field Name:',
};
