export default {
  appTitle: 'Business Central Setup',
  splashWelcome: 'Welcome! This wizard will help you configure Dynamics 365 Business Central.',
  getStarted: 'Get Started',
  basicInfoTitle: 'Basic Information',
  basicInfo: 'Basics',
  companyNameLabel: 'Company Name',
  industryLabel: 'Industry',
  websiteLabel: 'Website URL',
  descriptionLabel: 'Description',
  descriptionHint: 'Please tell us information about your company. It should be tall enough for 8 lines of text. This will help in providing the best possible configuration.',
  next: 'Next',
  back: 'Back',
  selectConfigArea: 'Select a configuration area',
  companyInfo: 'Company Information',
  generalLedgerSetup: 'General Ledger Setup',
  salesReceivablesSetup: 'Sales & Receivables Setup',
  purchasePayablesSetup: 'Purchases & Payables Setup',
  fixedAssetSetup: 'Fixed Asset Setup',
  common: 'Common',
  sometimes: 'Sometimes',
  additional: 'Additional',
  customers: 'Customers',
  vendors: 'Vendors',
  items: 'Items',
  currencies: 'Currencies',
  chartOfAccounts: 'Chart of Accounts',
  numberSeries: 'Number Series',
  hideUncommon: 'Hide uncommon settings',
  search: 'Search',
  help: 'Get Help from your Partner',
  review: 'Review',
  reviewAndFinish: 'Review and Finish',
  configurationData: 'Configuration Data',
  masterData: 'Master Data',
  configureTemplates: 'Configure Templates',
  finishTitle: 'Finish',
  finishGeneratePrompt: 'Click below to generate your RapidStart file.',
  generate: 'Generate',
  fileCreated: 'File created:',
  debugLog: 'Debug Log',
  home: 'Home',
  skip: 'Skip',
  skipSection: 'Skip Section',
  allCommonComplete: 'All common fields completed',
  finishButton: 'Confirm and Continue',
  bcFieldNameLabel: 'Business Central Field Name:',
  customerTemplate: 'Customer Template',
  vendorTemplate: 'Vendor Template',
  itemTemplate: 'Item Template',
  glAccountTemplate: 'G/L Account Template',
  bankAccountTemplate: 'Bank Account Template',
  fixedAssetTemplate: 'Fixed Asset Template',
  contactTemplate: 'Contact Template',
  employeeTemplate: 'Employee Template',
  resourceTemplate: 'Resource Template',
};
